version: 1
update_configs:

  - package_manager: docker
    directory: /
    update_schedule: daily
    commit_message:
      prefix: chore
      include_scope: true
    automerged_updates:
      - match:
          dependency_type: all
          update_type: 'semver:minor'
    default_labels:
      - ':recycle: Chore'

  - package_manager: javascript
    directory: /
    update_schedule: daily
    commit_message:
      prefix: chore
      include_scope: true
    automerged_updates:
      - match:
          dependency_type: all
          update_type: 'semver:minor'
    default_labels:
      - ':recycle: Chore'

  - package_manager: submodules
    directory: /
    update_schedule: daily
    commit_message:
      prefix: chore
      include_scope: true
    default_labels:
      - ':recycle: Chore'
