version: '3.4'

services:
  app:
    build:
      target: prod
      args:
        image_tag: ${IMAGE_TAG:-master}
    image: libero/article-store:${IMAGE_TAG:-master}
    environment:
      DATABASE_NAME: article-store
      DATABASE_USER: user
      DATABASE_PASSWORD: secret
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    depends_on:
      - db
  db:
    image: postgres:11.5-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: article-store
    ports:
      - '5432:5432'
    healthcheck:
      test: pg_isready --username user --dbnam article-store || exit 1
      interval: 5s
