version: '3.4'

services:
  app:
    build:
      target: dev
    image: libero/article-store:${IMAGE_TAG:-master}-dev
    environment:
      DATABASE_NAME: article-store
      DATABASE_USER: user
      DATABASE_PASSWORD: secret
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    volumes:
      - ../.eslintignore:/app/.eslintignore
      - ../.eslintrc.js:/app/.eslintrc.js
      - ../jest.config.js:/app/jest.config.js
      - ../src/:/app/src
      - ../package.json:/app/package.json
      - ../package-lock.json:/app/package-lock.json
      - ../test/:/app/test
      - ../tsconfig.json:/app/tsconfig.json
    depends_on:
      - db
  db:
    image: postgres:11.5-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: article-store
    ports:
      - '5432:5432'
    healthcheck:
      test: pg_isready --username user --dbnam article-store || exit 1
      interval: 5s
